wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - ${wp_public_port}:80

wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: ${mysql_root_pass}
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - ${phpmyadmin_public_port}:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: ${mysql_root_pass}